package frames;

import javax.swing.JOptionPane;
import models.SpecialVendingMachine;
import models.VendingMachine;


/**
 * The MainFrame class represents the main application frame.
 *
 * @author LIM, Theoni Anne
 *         TELOSA, Arwyn Gabrielle
 * @version 1.0
 * @since 07-22-2023
 */
public class MainFrame extends javax.swing.JFrame {

    private VendingMachine vendingMachine = null;
    
    
    /**
     * The MainFrame creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VendingMachineFactoryLbl = new javax.swing.JLabel();
        mainMenuPanel = new javax.swing.JPanel();
        createRegularBtn = new javax.swing.JButton();
        createSpecialBtn = new javax.swing.JButton();
        maintenanceTestBtn = new javax.swing.JButton();
        vendingFeaturesTestBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        VendingMachineFactoryLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        VendingMachineFactoryLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VendingMachineFactoryLbl.setText("Vending Machine Factory");
        VendingMachineFactoryLbl.setMaximumSize(new java.awt.Dimension(135, 30));
        VendingMachineFactoryLbl.setMinimumSize(new java.awt.Dimension(135, 30));
        VendingMachineFactoryLbl.setPreferredSize(new java.awt.Dimension(135, 30));

        mainMenuPanel.setPreferredSize(new java.awt.Dimension(400, 300));
        mainMenuPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 10));

       /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */        
        createRegularBtn.setText("Create Regular Vending Machine");
        createRegularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRegularBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(createRegularBtn);

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */       
        createSpecialBtn.setText("Create Special Vending Machine");
        createSpecialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSpecialBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(createSpecialBtn);
        
       /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        maintenanceTestBtn.setText("Maintenance Test");
        maintenanceTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceTestBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(maintenanceTestBtn);
        
       /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        vendingFeaturesTestBtn.setText("Vending Features Test");
        vendingFeaturesTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendingFeaturesTestBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(vendingFeaturesTestBtn);
        
       /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(exitBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(VendingMachineFactoryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(VendingMachineFactoryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action event for the 'createSpecialBtn' button.
     *
     * @param evt the action event triggered by the 'createSpecialBtn' button click.
     */
    private void createSpecialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSpecialBtnActionPerformed
        // TODO add your handling code here:
        if (vendingMachine != null){
            int result = JOptionPane.showConfirmDialog(null, "Vending Machine already exists, do you want to proceed?",
                    "Warning", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.NO_OPTION){
                return;
            }
        }
        
        vendingMachine = new SpecialVendingMachine();
        new PattyFrame(this, vendingMachine).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_createSpecialBtnActionPerformed

    /**
     * Handles the action event for the 'createRegularBtn' button.
     *
     * @param evt the action event triggered by the 'createRegularBtn' button click.
     */    
    private void createRegularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRegularBtnActionPerformed
        // TODO add your handling code here:
        
        if (vendingMachine != null){
            int result = JOptionPane.showConfirmDialog(null, "Vending Machine already exists, do you want to proceed?",
                    "Warning", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.NO_OPTION){
                return;
            }
        }
        
        vendingMachine = new VendingMachine();
        new AddItemFrame(this, vendingMachine).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_createRegularBtnActionPerformed
    
    /**
     * Handles the action event for the 'maintenanceTestBtn' button.
     *
     * @param evt the action event triggered by the 'maintenanceTestBtn' button click.
     */ 
    private void maintenanceTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceTestBtnActionPerformed
        // TODO add your handling code here:
        if (vendingMachine != null){
            new MaintenanceFrame(this, vendingMachine).setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Create a vending machine first!");
        }
    }//GEN-LAST:event_maintenanceTestBtnActionPerformed

    /**
     * Handles the action event for the 'vendingFeaturesTestBtn' button.
     *
     * @param evt the action event triggered by the 'vendingFeaturesTestBtn' button click.
     */
    private void vendingFeaturesTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendingFeaturesTestBtnActionPerformed
        // TODO add your handling code here:
        if (vendingMachine != null){
            new ReceivePaymentFrame(this, vendingMachine).setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Create a vending machine first!");
        }
    }//GEN-LAST:event_vendingFeaturesTestBtnActionPerformed

     /**
     * Handles the action event for the 'exitBtn' button.
     *
     * @param evt the action event triggered by the 'exitBtn' button click.
     */   
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VendingMachineFactoryLbl;
    private javax.swing.JButton createRegularBtn;
    private javax.swing.JButton createSpecialBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JButton maintenanceTestBtn;
    private javax.swing.JButton vendingFeaturesTestBtn;
    // End of variables declaration//GEN-END:variables
}
