package frames;

import items.Beef;
import items.Chicken;
import items.Item;
import items.Plant;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.VendingMachine;

/**
 * The PattyFrame Class represents the GUI for selecting the patties for the machine.
 *
 * @author LIM, Theoni Anne
 *         TELOSA, Arwyn Gabrielle
 * @version 1.0
 * @since 07-22-2023
 */
public class PattyFrame extends javax.swing.JFrame {

    private ArrayList<Item> itemList = new ArrayList();
    private VendingMachine vendingMachine;
    private MainFrame sourceFrame;

    /**
     * The PattyFrame Constructor creates new form PattyFrame
     * @param sourceFrame reference to main frame
     * @param vendingMachine current instance of vending machine
     */
    public PattyFrame(MainFrame sourceFrame, VendingMachine vendingMachine) {
        this.sourceFrame = sourceFrame;
        this.vendingMachine  = vendingMachine;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        beef = new javax.swing.JButton();
        chicken = new javax.swing.JButton();
        plant = new javax.swing.JButton();
        finish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Patty");

        jLabel1.setText("Select a patty to add");

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        beef.setText("Beef");
        beef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beefActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        chicken.setText("Chicken");
        chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        plant.setText("Plant");
        plant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(beef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chicken, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(plant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(beef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chicken)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant)
                .addGap(27, 27, 27)
                .addComponent(finish)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action event for the 'Chicken' button.
     *
     * @param evt the action event triggered by the 'setPrice' button click.
     */
    private void chickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenActionPerformed
        // TODO add your handling code here:
        itemList.add(new Chicken());
        chicken.setEnabled(false);
    }//GEN-LAST:event_chickenActionPerformed

    /**
     * Handles the action event for the 'Beef' button.
     *
     * @param evt the action event triggered by the 'setPrice' button click.
     */
    private void beefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beefActionPerformed
        // TODO add your handling code here:
            
        itemList.add(new Beef());
        beef.setEnabled(false);
    
    }//GEN-LAST:event_beefActionPerformed

    /**
     * Handles the action event for the 'Plant' button.
     *
     * @param evt the action event triggered by the 'setPrice' button click.
     */
    private void plantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantActionPerformed
        // TODO add your handling code here:
        itemList.add(new Plant());
        plant.setEnabled(false);
    }//GEN-LAST:event_plantActionPerformed

    /**
     * Handles the action event for the 'Finish' button.
     *
     * @param evt the action event triggered by the 'setPrice' button click.
     */
    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        if (itemList.size() == 0){
            JOptionPane.showMessageDialog(this, "Must have at least 1 patty.");
            return;

        }
        
        dispose();
        AddItemFrame addItemFrame = new AddItemFrame(sourceFrame, vendingMachine);
        addItemFrame.setItemList(itemList);
        addItemFrame.setVisible(true);
        
    }//GEN-LAST:event_finishActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beef;
    private javax.swing.JButton chicken;
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton plant;
    // End of variables declaration//GEN-END:variables
}
