package frames;

import javax.swing.*;
import models.SpecialVendingMachine;
import models.VendingMachine;

/**
 * The ReceivePaymentFrame Class represents the GUI for receiving user payment.
 *
 * @author LIM, Theoni Anne
 *         TELOSA, Arwyn Gabrielle
 * @version 1.0
 * @since 07-22-2023
 */
public class ReceivePaymentFrame extends javax.swing.JFrame {
    private int totalPayment;
    private int[] cashInStorage;
    private VendingMachine vendingMachine;
    private MainFrame sourceFrame;

    /**
     * The ReceivePaymentFrame Constructor creates new ReceivePaymentFrame
     * @param sourceFrame reference to main frame
     * @param vendingMachine instance of current vending machine
     */
    public ReceivePaymentFrame(MainFrame sourceFrame, VendingMachine vendingMachine) {
        this.sourceFrame = sourceFrame;
        this.vendingMachine = vendingMachine;
        initComponents();
        cashInStorage = new int[9];
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        this.setTitle("Payment");
        
        jLabel1 = new javax.swing.JLabel();
        denominationButton1 = new javax.swing.JButton();
        denominationButton2 = new javax.swing.JButton();
        denominationButton3 = new javax.swing.JButton();
        denominationButton4 = new javax.swing.JButton();
        denominationButton5 = new javax.swing.JButton();
        denominationButton6 = new javax.swing.JButton();
        denominationButton7 = new javax.swing.JButton();
        denominationButton8 = new javax.swing.JButton();
        denominationButton9 = new javax.swing.JButton();
        finishPaymentButton = new javax.swing.JButton();
        totalPaymentLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select which denominations you would like to pay in (pesos):");

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        denominationButton1.setText("PHP 1");
        denominationButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominationButton1ActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        denominationButton2.setText("PHP 5");
        denominationButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominationButton2ActionPerformed(evt);
            }   
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        denominationButton3.setText("PHP 10");
        denominationButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominationButton3ActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        denominationButton4.setText("PHP 20");
        denominationButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominationButton4ActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        denominationButton5.setText("PHP 50");
        denominationButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominationButton5ActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        denominationButton6.setText("PHP 100");
        denominationButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominationButton6ActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        denominationButton7.setText("PHP 200");
        denominationButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominationButton7ActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        denominationButton8.setText("PHP 500");
        denominationButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominationButton8ActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        denominationButton9.setText("PHP 1000");
        denominationButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominationButton9ActionPerformed(evt);
            }
        });

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        finishPaymentButton.setText("Finish Payment");
        finishPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishPaymentButtonActionPerformed(evt);
            }
        });

        totalPaymentLabel.setText("0");

        getContentPane().setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        getContentPane().add(jLabel1);
        getContentPane().add(denominationButton1);
        getContentPane().add(denominationButton2);
        getContentPane().add(denominationButton3);
        getContentPane().add(denominationButton4);
        getContentPane().add(denominationButton5);
        getContentPane().add(denominationButton6);
        getContentPane().add(denominationButton7);
        getContentPane().add(denominationButton8);
        getContentPane().add(denominationButton9);
        getContentPane().add(finishPaymentButton);
        getContentPane().add(totalPaymentLabel);

        pack();
    }
    
    /**
     * Handles the action event for the 'denominationButton1' button.
     * Increments the total payment by 1
     *
     * @param evt the action event triggered by the 'denominationButton1' button click.
     */
    private void denominationButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        totalPayment += 1;
        cashInStorage[0]++;
        totalPaymentLabel.setText(String.valueOf(totalPayment));
    }

    /**
     * Handles the action event for the 'denominationButton2' button.
     * Increments the total payment by 5
     *
     * @param evt the action event triggered by the 'denominationButton2' button click.
     */
    private void denominationButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        totalPayment += 5;
        cashInStorage[1]++;
        totalPaymentLabel.setText(String.valueOf(totalPayment));
    }   

    /**
     * Handles the action event for the 'denominationButton3' button.
     * Increments the total payment by 10
     *
     * @param evt the action event triggered by the 'denominationButton3' button click.
     */
    private void denominationButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        totalPayment += 10;
        cashInStorage[2]++;
        totalPaymentLabel.setText(String.valueOf(totalPayment));
    }

    /**
     * Handles the action event for the 'denominationButton4' button.
     * Increments the total payment by 20
     *
     * @param evt the action event triggered by the 'denominationButton4' button click.
     */
    private void denominationButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        totalPayment += 20;
        cashInStorage[3]++;
        totalPaymentLabel.setText(String.valueOf(totalPayment));
    }

    /**
     * Handles the action event for the 'denominationButton5' button.
     * Increments the total payment by 50
     *
     * @param evt the action event triggered by the 'denominationButton5' button click.
     */
    private void denominationButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        totalPayment += 50;
        cashInStorage[4]++;
        totalPaymentLabel.setText(String.valueOf(totalPayment));
    }

    /**
     * Handles the action event for the 'denominationButton6' button.
     * Increments the total payment by 100
     *
     * @param evt the action event triggered by the 'denominationButton6' button click.
     */
    private void denominationButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        totalPayment += 100;
        cashInStorage[5]++;
        totalPaymentLabel.setText(String.valueOf(totalPayment));
    }

    /**
     * Handles the action event for the 'denominationButton7' button.
     * Increments the total payment by 200
     *
     * @param evt the action event triggered by the 'denominationButton7' button click.
     */
    private void denominationButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        totalPayment += 200;
        cashInStorage[6]++;
        totalPaymentLabel.setText(String.valueOf(totalPayment));
    }

    /**
     * Handles the action event for the 'denominationButton8' button.
     * Increments the total payment by 500
     *
     * @param evt the action event triggered by the 'denominationButton8' button click.
     */
    private void denominationButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        totalPayment += 500;
        cashInStorage[7]++;
        totalPaymentLabel.setText(String.valueOf(totalPayment));
    }

    /**
     * Handles the action event for the 'denominationButton9' button.
     * Increments the total payment by 1000
     *
     * @param evt the action event triggered by the 'denominationButton9' button click.
     */
    private void denominationButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        totalPayment += 1000;
        cashInStorage[8]++;
        totalPaymentLabel.setText(String.valueOf(totalPayment));
    }

    /**
     * Handles the action event for the 'Finish Payment' button.
     *
     * @param evt the action event triggered by the 'Finish Payment' button click.
     */
    private void finishPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Thank you for your payment of PHP " + totalPayment + "!");
        dispose();
        vendingMachine.receivePayment(cashInStorage, totalPayment);
        if (vendingMachine.getClass().getSimpleName().equals("VendingMachine")){
            
            new SelectItemFrame(sourceFrame, vendingMachine).setVisible(true);
        } else {
            new SpecialVMMenuFrame(sourceFrame, (SpecialVendingMachine) vendingMachine).setVisible(true);
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton denominationButton1;
    private javax.swing.JButton denominationButton2;
    private javax.swing.JButton denominationButton3;
    private javax.swing.JButton denominationButton4;
    private javax.swing.JButton denominationButton5;
    private javax.swing.JButton denominationButton6;
    private javax.swing.JButton denominationButton7;
    private javax.swing.JButton denominationButton8;
    private javax.swing.JButton denominationButton9;
    private javax.swing.JButton finishPaymentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel totalPaymentLabel;
    // End of variables declaration
}
