package frames;


import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.VendingMachine;

/**
 * The SetPriceFrame Class represents the GUI for setting the price of an item
 *
 * @author LIM, Theoni Anne
 *         TELOSA, Arwyn Gabrielle
 * @version 1.0
 * @since 07-22-2023
 */
public class SetPriceFrame extends javax.swing.JFrame {

    private VendingMachine vendingMachine;
    private MaintenanceFrame sourceFrame;

    
    
    /**
     * The SetPriceFrame constrcuts the menu for the set price option.
     *
     * @param sourceFrame reference to maintenance frame
     * @param vendingMachine instance of current vending machine
     */
    public SetPriceFrame(MaintenanceFrame sourceFrame, VendingMachine vendingMachine) {
        this.sourceFrame = sourceFrame;
        this.vendingMachine = vendingMachine;
        initComponents();
        displayItems();
    }
    
    /**
     * Displays all the items in the vending machine along with information for each.
     */
    public void displayItems(){
          for (String itemName : vendingMachine.getItems().keySet()){
            JPanel subPanel = new JPanel();
            subPanel.setLayout(new GridLayout(5, 1, 2, 2));
            
            JLabel nameLbl = new JLabel(itemName);
            nameLbl.setFont(new Font("Arial", Font.PLAIN, 20));
            
            JLabel quantityLbl = new JLabel("Quantity: " + Integer.toString(vendingMachine.getItems().get(itemName).size()-1));
            quantityLbl.setFont(new Font("Arial", Font.PLAIN, 20));

            
            JLabel caloriesLbl = new JLabel("Calories: " + Float.toString(vendingMachine.getItems().get(itemName).get(0).getCalories()));
            caloriesLbl.setFont(new Font("Arial", Font.PLAIN, 20));

            
            JLabel priceLbl = new JLabel("Price: P" + Integer.toString( vendingMachine.getItems().get(itemName).get(0).getPrice()));
            priceLbl.setFont(new Font("Arial", Font.PLAIN, 20));
            
            JButton btn = new JButton();
            btn.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    int price = getInteger();
                    vendingMachine.setPrice(itemName, price);
                    priceLbl.setText("Price: P" + Integer.toString( vendingMachine.getItems().get(itemName).get(0).getPrice()));
                }
                
            });
            btn.setText("Set Price");

            
            subPanel.add(btn);
            subPanel.add(nameLbl);
            subPanel.add(quantityLbl);
            subPanel.add(caloriesLbl);
            subPanel.add(priceLbl);
            mainPanel.add(subPanel);
        }
    }

    /**
     * Prompts the user for an integer input and returns the value.
     *
     * @return The user's input as an Integer, or null if the input was not a valid integer.
     */
     private Integer getInteger() {
        String input = JOptionPane.showInputDialog(null, "Enter an integer:");

        try {
            int price = Integer.parseInt(input);
            return price;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid integer.");
            return null;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promptLbl = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        finish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Set Price");

        promptLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        promptLbl.setText("Which item do you want to set the price of?");

        mainPanel.setLayout(new java.awt.GridLayout(5, 2, 0, 10));

         /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(promptLbl)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(promptLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Handles the action when the 'finish' button is pressed.
     * 
     * @param evt The event triggered by pressing the 'finish' button.
     */
    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        dispose();
        sourceFrame.setVisible(true);
    }//GEN-LAST:event_finishActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finish;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel promptLbl;
    // End of variables declaration//GEN-END:variables
}
