package frames;


import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.VendingMachine;

/**
 * The StockFrame Class represents the GUI for stocking an item
 *
 * @author LIM, Theoni Anne
 *         TELOSA, Arwyn Gabrielle
 * @version 1.0
 * @since 07-22-2023
 */
public class StockFrame extends javax.swing.JFrame {

    private VendingMachine vendingMachine = null;
    private MaintenanceFrame sourceFrame = null;
    
    
    /**
     * The StockFrame method creates new form StockFrame
     * @param sourceFrame
     * @param vendingMachine
     */
    public StockFrame(MaintenanceFrame sourceFrame, VendingMachine vendingMachine) {
        this.sourceFrame = sourceFrame;
        this.vendingMachine = vendingMachine;
        initComponents();
        displayItems();
    }
    
    /**
     * Displays each item in vending machine along with corresponding information.
     */
    public void displayItems(){
        for (String itemName : vendingMachine.getItems().keySet()){
            JPanel subPanel = new JPanel();
            subPanel.setLayout(new GridLayout(5, 1, 2, 2));
            
            JLabel nameLbl = new JLabel(itemName);
            nameLbl.setFont(new Font("Arial", Font.PLAIN, 20));
            
            JLabel quantityLbl = new JLabel("Quantity: " + Integer.toString(vendingMachine.getItems().get(itemName).size()-1));
            quantityLbl.setFont(new Font("Arial", Font.PLAIN, 20));

            
            JLabel caloriesLbl = new JLabel("Calories: " + Float.toString(vendingMachine.getItems().get(itemName).get(0).getCalories()));
            caloriesLbl.setFont(new Font("Arial", Font.PLAIN, 20));

            
            JLabel priceLbl = new JLabel("Price: P" + Float.toString( vendingMachine.getItems().get(itemName).get(0).getPrice()));
            priceLbl.setFont(new Font("Arial", Font.PLAIN, 20));
            
            JButton btn = new JButton();
            btn.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    vendingMachine.stock(vendingMachine.getItems().get(itemName).get(0));
                    quantityLbl.setText("Quantity: " + Integer.toString(vendingMachine.getItems().get(itemName).size()-1));
                }
                
            });
            btn.setText("Stock");

            
            subPanel.add(btn);
            subPanel.add(nameLbl);
            subPanel.add(quantityLbl);
            subPanel.add(caloriesLbl);
            subPanel.add(priceLbl);
            mainPanel.add(subPanel);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promptLbl = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        finishStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock");

        promptLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        promptLbl.setText("Which item do you want to stock?");

        mainPanel.setLayout(new java.awt.GridLayout(5, 2, 0, 10));

        finishStock.setText("Finish Stocking");
        finishStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(promptLbl)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(finishStock, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(promptLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action event for the 'Finish Stock' button.
     *
     * @param evt the action event triggered by the 'Finish Stock' button click.
     */
    private void finishStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishStockActionPerformed
        // TODO add your handling code here:
        dispose();
        sourceFrame.setVisible(true);
    }//GEN-LAST:event_finishStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finishStock;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel promptLbl;
    // End of variables declaration//GEN-END:variables
}
