package frames;


import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import models.Transaction;
import models.VendingMachine;

/**
 * The TransactionSummaryFrame Class displays transaction summary along with inventory since last restocking.
 *
 * @author LIM, Theoni Anne
 *         TELOSA, Arwyn Gabrielle
 * @version 1.0
 * @since 07-22-2023
 */
public class TransactionSummaryFrame extends javax.swing.JFrame {

    private VendingMachine vendingMachine;
    private MaintenanceFrame sourceFrame;
    
    
    /**
     * The TransactionSummaryFrame Constructor creates a new Transaction Summary GUI
     * @param sourceFrame reference to maintenance frame
     * @param vendingMachine instance of current vending machine
     */
    public TransactionSummaryFrame(MaintenanceFrame sourceFrame, VendingMachine vendingMachine) {
        this.vendingMachine = vendingMachine;
        this.sourceFrame = sourceFrame;
        initComponents();
        String[] transactions = new String[vendingMachine.getTransactions().size()];
        for (int i = 0; i < transactions.length; i++){
            Transaction t = vendingMachine.getTransactions().get(i);
            transactions[i] = "P" + t.getPrice() + "    " + t.getItemBought();
        }
        itemList.setModel(new DefaultComboBoxModel(transactions));
        
        for (String itemName : vendingMachine.getItems().keySet()){
            inventoryText.append((vendingMachine.getItems().get(itemName).size()-1) + " " + itemName + "\n");
        }
    }
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList<>();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryText = new javax.swing.JTextArea();
        inventoryLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transaction Summary");

        title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        title.setText("Transaction Summary");

        itemList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scrollPane.setViewportView(itemList);

        /**
         * Handles the action event triggered by a UI component.
         * 
         * @param evt the action event that was triggered
         */
        back.setText("Back to Menu");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        inventoryText.setColumns(20);
        inventoryText.setRows(5);
        jScrollPane1.setViewportView(inventoryText);

        inventoryLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inventoryLbl.setText("Inventory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inventoryLbl)
                        .addGap(149, 149, 149))))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(inventoryLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action event for the 'back' button.
     *
     * @param evt the action event triggered by the 'back' button click.
     */
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dispose();
        sourceFrame.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel inventoryLbl;
    private javax.swing.JTextArea inventoryText;
    private javax.swing.JList<String> itemList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
